# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AnswerSystem' do
    use_frameworks!
    pod 'YYText'
    pod 'YYImage'
end

